version: "3.9"
services:
    adminer:
        image: adminer
        restart: always
        ports:
            - "23097:8080"
    backend:
        # image: node:20-bullseye
        build: ./backend
        working_dir: /backend
        # command: sh -c "yarn prisma db push && node lib/cli"
        restart: always
        depends_on:
            - db
        ports:
            - "23095:23095"
        volumes:
            - ./backend:/backend
            - ./data/backend/root:/root
        environment:
            DATABASE_URL: mysql://root:${DB_PASSWORD}@db/iscamp
            PORT: 23095
            URL_BASE: ${URL_BASE}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_USER: ${MAIL_USER}
            MAIL_PASS: ${MAIL_PASS}
    db:
        image: mariadb:latest
        restart: always
        volumes:
            - ./data/db:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    frontend:
        image: node:20-bullseye
        working_dir: /frontend
        command: sh -c "yarn preview --host"
        restart: always
        depends_on:
            - backend
        volumes:
            - ./prokop-frontend:/frontend
